# Site settings
title: A study on what helps catch the attention of modern day fickle newsreaders
author: 
  name: Chkroun   
  email: kaourintin.tamine@epfl.ch
author: 
  name:  Oliveri  
  email: kaourintin.tamine@epfl.ch
author: 
  name:   Lazzaroni 
  email: kaourintin.tamine@epfl.ch
author: 
  name: Tamine   
  email: kaourintin.tamine@epfl.ch
description: "A project on the quotebank dataset"

# Build settings
remote_theme: jekyll/minima
